FormUpdated/Areas/BillingSystem/Controllers/SecondaryTable/RejectionsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FormUpdated.Areas.BillingSystem.Models;

namespace FormUpdated.Areas.BillingSystem.Controllers
{
    [Authorize]
    [Route("Area/BillingSystem")]
    public class RejectionsController : Controller
    {
        private ILogger logger;
        private BillingSystemEntities db = new BillingSystemEntities();

        public RejectionsController()
        {
            logger = log.GetInstance;
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            string folderPath = System.Configuration.ConfigurationManager.AppSettings["ErrorFolder"];
            folderPath = Server.MapPath(folderPath);

            logger.LogExceptions(filterContext.Exception, folderPath);

            filterContext.ExceptionHandled = true;
            this.View("Error").ExecuteResult(this.ControllerContext);
        }

        public ActionResult CusRegUpload()
        {
            return View();
        }

        public ActionResult LesRegUpload()
        {
            return View();
        }

        #region Upload cus Reg
        [HttpPost]
        public ActionResult UploadCusReg()
        {
            string Message = string.Empty;

            // Checking no of files injected in Request object  
            if (Request.Files.Count > 0)
            {
                try
                {
                    //  Get all files from Request object  
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {
                        //string path = AppDomain.CurrentDomain.BaseDirectory + "Uploads/";  
                        //string filename = Path.GetFileName(Request.Files[i].FileName);  

                        HttpPostedFileBase file = files[i];
                        string fname;

                        // Checking for Internet Explorer  
                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {
                            string[] testfiles = file.FileName.Split(new char[] { '\\' });
                            fname = testfiles[testfiles.Length - 1];
                        }
                        else
                        {
                            fname = file.FileName;
                        }

                        // Get the complete folder path and store the file inside it.  
                        //fname = Path.Combine(Server.MapPath("~/Uploads/"), fname);
                        string tempPath = System.IO.Path.GetTempPath() + Guid.NewGuid().ToString() + fname;
                        file.SaveAs(tempPath);

                        Helper.Dummy_Helper helper = new Helper.Dummy_Helper();
                        Message = helper.CusRegUpload(tempPath);
                        //List<int> lstID = helper.EvoSatCDR2CT(tempPath, lesid); //new List<int> { 58 };

                        //if (lstID.Count > 0)
                        //  Message = helper.RejectionCondition_EvoSat(lstID);
                        //else
                        //  return Json("NSSL CDR Getting Error, it not return Master Primary ID.", JsonRequestBehavior.AllowGet);
                    }
                    // Returns message that successfully uploaded  
                    return Json(Message, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    return Json("Error occurred. Error details: " + ex.Message, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json("No files selected.", JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        #region Upload Les Reg
        [HttpPost]
        public ActionResult UploadLesReg()
        {
            string Message = string.Empty;

            // Checking no of files injected in Request object  
            if (Request.Files.Count > 0)
            {
                try
                {
                    //  Get all files from Request object  
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {
                        //string path = AppDomain.CurrentDomain.BaseDirectory + "Uploads/";  
                        //string filename = Path.GetFileName(Request.Files[i].FileName);  

                        HttpPostedFileBase file = files[i];
                        string fname;

                        // Checking for Internet Explorer  
                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {
                            string[] testfiles = file.FileName.Split(new char[] { '\\' });
                            fname = testfiles[testfiles.Length - 1];
                        }
                        else
                        {
                            fname = file.FileName;
                        }

                        // Get the complete folder path and store the file inside it.  
                        //fname = Path.Combine(Server.MapPath("~/Uploads/"), fname);
                        string tempPath = System.IO.Path.GetTempPath() + Guid.NewGuid().ToString() + fname;
                        file.SaveAs(tempPath);

                        Helper.Dummy_Helper helper = new Helper.Dummy_Helper();
                        Message = helper.LesRegUpload(tempPath);
                        //List<int> lstID = helper.EvoSatCDR2CT(tempPath, lesid); //new List<int> { 58 };

                        //if (lstID.Count > 0)
                        //  Message = helper.RejectionCondition_EvoSat(lstID);
                        //else
                        //  return Json("NSSL CDR Getting Error, it not return Master Primary ID.", JsonRequestBehavior.AllowGet);
                    }
                    // Returns message that successfully uploaded  
                    return Json(Message, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    return Json("Error occurred. Error details: " + ex.Message, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json("No files selected.", JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        // GET: BillingSystem/Rejections
        public ActionResult Index()
        {
            return View(db.Bst1A.ToList());
        }

        public ActionResult Rejection()
        {
            return View(db.BS1ALessT.ToList());
        }

        [HttpPost]
        public ActionResult MovetoInvoice(string[] lists)
        {
            List<Tuple<bool, string>> Msg = new List<Tuple<bool, string>>();
            if (lists.Length > 0)
            {
                foreach (string id in lists)
                {
                    helper_NSSLGlobal billingHelpers = new helper_NSSLGlobal();

                    int value = 0;
                    if (int.TryParse(id, out value))
                    {
                        Msg = billingHelpers.Move2Invoice(value);
                    }
                }
            }

            string returnmsg = string.Empty;
            foreach (var tupl in Msg)
            {
                if (tupl.Item1)
                    returnmsg += string.Format("{0} Succefully moved to Invoice", tupl.Item2);
                else
                    returnmsg += string.Format("{0} Not Succefully move to Invoice", tupl.Item2);
            }

            return Json(returnmsg, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ViewRejectionLog(string[] lists)
        {
            System.Text.StringBuilder Message = new System.Text.StringBuilder();
            if (lists.Length > 0)
            {
                foreach (string id in lists)
                {
                    int value = 0;
                    if (int.TryParse(id, out value))
                    {
                        try
                        {
                            var msgs = db.BS1LesRejLog.FirstOrDefault(t => t.fkBs1LesReg == value).Bs1lesRejection;
                            Message.Append(msgs).AppendLine();
                        }
                        catch { }
                    }
                }
            }
            return Json(Message.ToString(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Index(string[] lists)
        {
            if (lists.Length > 0)
            {
                foreach (string id in lists)
                {
                    BillingHelpers billingHelpers = new BillingHelpers();

                    int value = 0;
                    if (int.TryParse(id, out value))
                    {
                        billingHelpers.MoveRejection_Invoice(value);
                    }
                }
            }
            return RedirectToAction("Index");
        }

        public List<UploadFiles> getCdrfiles()
        {
            List<UploadFiles> lstfiles = new List<UploadFiles>();

            string folderPath = Server.MapPath("../CDR Files/");
            int i = 1;

            foreach (string file in System.IO.Directory.EnumerateFiles(folderPath, "*.csv"))
            {
                UploadFiles up = new UploadFiles();
                up.id = i++;
                up.location = file;
                up.Filename = Path.GetFileName(file);
                lstfiles.Add(up);
            }

            foreach (string file in System.IO.Directory.EnumerateFiles(folderPath, "*.xlsx"))
            {

FormUpdated/Areas/BillingSystem/Views/Rejections/CusRegUpload.cshtml
@{
    ViewBag.Title = "Cus Reg Upload";
    Layout = "~/Areas/BillingSystem/Views/Shared/_Loyout_BS.cshtml";
}


<style type="text/css">
    .image-upload {
        padding-left: 20px;
        display: inline-block;
    }

        .image-upload > input {
            display: block;
        }

    .modal {
        position: fixed;
        z-index: 1000;
        height: 100%;
        width: 100%;
        top: 0;
        background-color: Black;
        filter: alpha(opacity=60);
        opacity: 0.6;
        -moz-opacity: 0.8;
        display: none;
    }

    .center {
        z-index: 1000;
        margin: 50px auto;
        padding: 10px;
        height: 100%;
        width: 100%;
        background-color: White;
        border-radius: 10px;
        filter: alpha(opacity=100);
        opacity: 1;
        -moz-opacity: 1;
    }

    .centerimg {
        height: 100%;
        width: 100%;
        display: inline-block;
        position: inherit;
    }

    .fileUpload {
        position: relative;
        overflow: hidden;
        margin: 10px;
    }

        .fileUpload input.upload {
            position: absolute;
            top: 0;
            right: 0;
            margin: 0;
            padding: 0;
            font-size: 20px;
            cursor: pointer;
            opacity: 0;
            filter: alpha(opacity=0);
        }
</style>

<div class="container">
    <div class="panel panel-primary">
        <div class="panel panel-heading fontStyle"> <p> Cus Reg Upload </p> </div>
        <div class="panel-body">

            <div id="progress" class="modal">
                <div class="center" align="center">
                    <img src="~/Images/image-loader.gif" class="centerimg" />
                </div>
            </div>

            @using (Html.BeginForm())
            {
                <div>
                    <table style="width:500px;padding:10px;">
                        <tr>
                            <td style="padding:10px;">
                                <span class="fontStyle" style="color:black !important;"> Upload Cus Reg  </span>
                            </td>
                            <td>
                                <input type="file" id="uploadFile" class="btn btn-default" />
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;"></td>
                            <td>
                                <input type="button" id="btnUpload" value="Upload" class="btn btn-primary btn-lg btn-block" style="width:100%;" />
                            </td>
                        </tr>
                    </table>
                </div>

                <br />
                <div>
                    <div>
                        @*@Html.ActionLink("Data and Voice List", "ImarSatDBView", null, new { @class = "btn btn-primary" })*@
                    </div>
                </div>
            }


            <div id="dialog" title="CDR Invoices Status">
                <div id="divMsg">

                </div>
                <hr />
                <div align="center">
                    <input type="button" id="btnClose" value="OK" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {

    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/CSSjqueryUI")

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryUI")

    <script type="text/javascript">

        $(document).ready(function () {

            $(function () {
                $("#dialog").dialog({
                    resizable: false,
                    autoOpen: false,
                    height: "auto",
                    width: 750,
                    modal: true,
                }).prev(".ui-dialog-titlebar").css("background", "#337ab7").css("color", "#F5F5F5");
            });

            $("#btnClose").click(function () {
                $("#dialog").dialog("close");
            });

            //------------------------------- Upload ImarSat File to CT Start Process ----------------------------//

            $("#btnUpload").click(function () {
                $(".modal").css("display", "block");
                gotoAction();
            });

            function gotoAction() {

                // Checking whether FormData is available in browser
                if (window.FormData !== undefined) {
                    var fileUpload = $("#uploadFile").get(0);
                    var files = fileUpload.files;

                    // Create FormData object
                    var fileData = new FormData();

                    // Looping over all files and add it to FormData object
                    for (var i = 0; i < files.length; i++) {
                        fileData.append(files[i].name, files[i]);
                    }

                    var LES;
                    var list = {};
                    //LES = list.LesRef = $('#LES_Ref option:selected').val();
                    //list.SatType = $('#Satellite_Type option:selected').val();
                    //list.EquipType = $('#Equipment_Type option:selected').val();

                    //fileData.append("LES_Ref", LES);
                    // Adding one more key to FormData object
                    //fileData.append('username', ‘Manas’);

                    $.ajax({
                        url:'@Url.Action("UploadCusReg", "Rejections")',
                        type: "POST",
                        contentType: false, // Not to set any content header
                        processData: false, // Not to process data
                        data: fileData,
                        success: function (result) {
                            $(".modal").css("display", "none");
                            $("#divMsg").html(result);
                            $("#dialog").dialog("open");
                        },
                        error: function (xhr, status, text) {
                            $(".modal").css("display", "none");
                            var xhrsataus = xhr.status;
                            alert("Error: xhr status: " + xhrsataus + " status: " + status + " text: " + text);
                        }
                    });
                }
                else {
                    $(".modal").css("display", "none");
                    alert("FormData is not supported.");
                }
                //return false;
            }

            //------------------------------- Upload NSSL File to CT End Process ----------------------------//
        });
    </script>
}

FormUpdated/Areas/BillingSystem/Views/Rejections/LesRegUpload.cshtml
@{
    ViewBag.Title = "LES Reg Upload";
    Layout = "~/Areas/BillingSystem/Views/Shared/_Loyout_BS.cshtml";
}


<style type="text/css">
    .image-upload {
        padding-left: 20px;
        display: inline-block;
    }

        .image-upload > input {
            display: block;
        }

    .modal {
        position: fixed;
        z-index: 1000;
        height: 100%;
        width: 100%;
        top: 0;
        background-color: Black;
        filter: alpha(opacity=60);
        opacity: 0.6;
        -moz-opacity: 0.8;
        display: none;
    }

    .center {
        z-index: 1000;
        margin: 50px auto;
        padding: 10px;
        height: 100%;
        width: 100%;
        background-color: White;
        border-radius: 10px;
        filter: alpha(opacity=100);
        opacity: 1;
        -moz-opacity: 1;
    }

    .centerimg {
        height: 100%;
        width: 100%;
        display: inline-block;
        position: inherit;
    }

    .fileUpload {
        position: relative;
        overflow: hidden;
        margin: 10px;
    }

        .fileUpload input.upload {
            position: absolute;
            top: 0;
            right: 0;
            margin: 0;
            padding: 0;
            font-size: 20px;
            cursor: pointer;
            opacity: 0;
            filter: alpha(opacity=0);
        }
</style>

<div class="container">
    <div class="panel panel-primary">
        <div class="panel panel-heading fontStyle"> <p> Les Reg Upload </p> </div>
        <div class="panel-body">

            <div id="progress" class="modal">
                <div class="center" align="center">
                    <img src="~/Images/image-loader.gif" class="centerimg" />
                </div>
            </div>

            @using (Html.BeginForm())
            {
                <div>
                    <table style="width:500px;padding:10px;">
                        <tr>
                            <td style="padding:10px;">
                                <span class="fontStyle" style="color:black !important;"> Upload Les Reg  </span>
                            </td>
                            <td>
                                <input type="file" id="uploadFile" class="btn btn-default" />
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;"></td>
                            <td>
                                <input type="button" id="btnUpload" value="Upload" class="btn btn-primary btn-lg btn-block" style="width:100%;" />
                            </td>
                        </tr>
                    </table>
                </div>

                <br />
                <div>
                    <div>
                        @*@Html.ActionLink("Data and Voice List", "ImarSatDBView", null, new { @class = "btn btn-primary" })*@
                    </div>
                </div>
            }


            <div id="dialog" title="CDR Invoices Status">
                <div id="divMsg">

                </div>
                <hr />
                <div align="center">
                    <input type="button" id="btnClose" value="OK" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {

    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/CSSjqueryUI")

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryUI")

    <script type="text/javascript">

        $(document).ready(function () {

            $(function () {
                $("#dialog").dialog({
                    resizable: false,
                    autoOpen: false,
                    height: "auto",
                    width: 750,
                    modal: true,
                }).prev(".ui-dialog-titlebar").css("background", "#337ab7").css("color", "#F5F5F5");
            });

            $("#btnClose").click(function () {
                $("#dialog").dialog("close");
            });

            //------------------------------- Upload ImarSat File to CT Start Process ----------------------------//

            $("#btnUpload").click(function () {
                $(".modal").css("display", "block");
                gotoAction();
            });

            function gotoAction() {

                // Checking whether FormData is available in browser
                if (window.FormData !== undefined) {
                    var fileUpload = $("#uploadFile").get(0);
                    var files = fileUpload.files;

                    // Create FormData object
                    var fileData = new FormData();

                    // Looping over all files and add it to FormData object
                    for (var i = 0; i < files.length; i++) {
                        fileData.append(files[i].name, files[i]);
                    }

                    var LES;
                    var list = {};
                    //LES = list.LesRef = $('#LES_Ref option:selected').val();
                    //list.SatType = $('#Satellite_Type option:selected').val();
                    //list.EquipType = $('#Equipment_Type option:selected').val();

                    //fileData.append("LES_Ref", LES);
                    // Adding one more key to FormData object
                    //fileData.append('username', ‘Manas’);

                    $.ajax({
                        url:'@Url.Action("UploadLesReg", "Rejections")',
                        type: "POST",
                        contentType: false, // Not to set any content header
                        processData: false, // Not to process data
                        data: fileData,
                        success: function (result) {
                            $(".modal").css("display", "none");
                            $("#divMsg").html(result);
                            $("#dialog").dialog("open");
                        },
                        error: function (xhr, status, text) {
                            $(".modal").css("display", "none");
                            var xhrsataus = xhr.status;
                            alert("Error: xhr status: " + xhrsataus + " status: " + status + " text: " + text);
                        }
                    });
                }
                else {
                    $(".modal").css("display", "none");
                    alert("FormData is not supported.");
                }
                //return false;
            }

            //------------------------------- Upload NSSL File to CT End Process ----------------------------//
        });
    </script>
}

FormUpdated/Areas/BillingSystem/Views/Rejections/otesatCdr2Ct.cshtml
@{
    ViewBag.Title = "otesatCdr2Ct";
    Layout = "~/Areas/BillingSystem/Views/Shared/_Loyout_BS.cshtml";
}

<style type="text/css">
    .image-upload {
        padding-left: 20px;
        display: inline-block;
    }

        .image-upload > input {
            display: block;
        }

    .modal {
        position: fixed;
        z-index: 1000;
        height: 100%;
        width: 100%;
        top: 0;
        background-color: Black;
        filter: alpha(opacity=60);
        opacity: 0.6;
        -moz-opacity: 0.8;
        display: none;
    }

    .center {
        z-index: 1000;
        margin: 50px auto;
        padding: 10px;
        height: 100%;
        width: 100%;
        background-color: White;
        border-radius: 10px;
        filter: alpha(opacity=100);
        opacity: 1;
        -moz-opacity: 1;
    }

    .centerimg {
        height: 100%;
        width: 100%;
        display: inline-block;
        position: inherit;
    }

    .fileUpload {
        position: relative;
        overflow: hidden;
        margin: 10px;
    }

        .fileUpload input.upload {
            position: absolute;
            top: 0;
            right: 0;
            margin: 0;
            padding: 0;
            font-size: 20px;
            cursor: pointer;
            opacity: 0;
            filter: alpha(opacity=0);
        }
</style>

<div>
    @{ var fileName = string.Empty;}
    @if (ViewBag.File != null)
    {
        fileName = ViewBag.File;
    }

    @{ var Error = string.Empty;}
    @if (ViewBag.Msg != null)
    {
        Error = ViewBag.Msg;
    }

    <div class="container">
        <div class="panel panel-primary">
            <div class="panel panel-heading fontStyle"> <p> Test OteSat CDR to CT </p> </div>
            <div class="panel-body">

                <div id="progress" class="modal">
                    <div class="center" align="center">
                        <img src="~/Images/image-loader.gif" class="centerimg" />
                    </div>
                </div>

                @Html.Label("lblmsg", Error, new { @class="label-danger"})
                <br />

                <div>
                    @using(Html.BeginForm("RemoveCT", "Rejections", FormMethod.Post))
                    {
                    <p>
                        Please Remove the Common Table before proceeding to upload CDR for avoiding duplicate entry
                    </p>
                    <input type="submit" id="btnremovect" value="click here to remove CT" class="btn btn-link" />
                    }
                </div>
                <br />
                <div>
                    <div class="form-group">
                        @Html.Label("LES Ref", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("LES Ref", (IEnumerable<SelectListItem>)ViewBag.LESRef, null, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <br />
                <div>
                    @using (Html.BeginForm("toCT", "Rejections", FormMethod.Post))
                    {
                        <table>
                            <tr>
                                <td>
                                    OteSat File Name:
                                </td>
                                <td>
                                    @Html.TextBox("txtfilesName", fileName, new { @class = "form-control" })
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td style="padding:20px;">
                                    <input type="submit" id="btnGen" value="Submit" class="btn btn-success" />
                                </td>
                            </tr>
                        </table>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {

    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/CSSjqueryUI")

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryUI")

    <script type="text/javascript">
        $(document).ready(function () {
            $("#submit").click(function () {
                $(".modal").css("display", "block");
            });
        });

    </script>
}

FormUpdated/Areas/BillingSystem/Views/Rejections/otesatCdrSave.cshtml
@{
    ViewBag.Title = "CDR Save";
    Layout = "~/Areas/BillingSystem/Views/Shared/_Loyout_BS.cshtml";
}

<div>
    @{string msg = string.Empty; }

    @if (ViewBag.Msg != null)
    {
        msg = ViewBag.Msg;
    }

    <div>
        @Html.Label("lblMsg", msg, new { @class = "label-danger"})
    </div>
    <br />
    <div>
        @using (Html.BeginForm("RemoveCDR", "Rejections", FormMethod.Post))
        {
            <p>
                Please remove the CDR excel file before proceeding, it will avoid to duplicate entry.
            </p>
            <input type="submit" id="btnremovect" value="click here to remove CDR" class="btn btn-link" />
        }
    </div>
    <br />
</div>
<div>
    <div class="form-group">
        <div class="image-upload">
            <div class="fileUpload">
                <input type="file" id="uploadfile" class="btn btn-default" />
                <br />
                <button type="button" id="btnUpload" value="Upload" class="btn btn-success">Upload</button>
                <span class="fontStyle" style="color:black !important;vertical-align:top;"> Upload OteSat to Save  </span>
            </div>
        </div>
    </div>
</div>


@section scripts{
    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/CSSjqueryUI")

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryUI")

    <script type="text/javascript">
        $(document).ready(function () {
                $("#btnUpload").click(function () {
               // $(".modal").css("display", "block");
                gotoAction();
                });

            function gotoAction() {
                //Checking whether form data is available in browser
                if (window.FormData !== undefined) {
                    var fileupload = $("#uploadfile").get(0);
                    var files = fileupload.files;

                    // Create formdata object
                    var formdata = new FormData();

                    // Looping over all files and it to the formdata
                    for (var i = 0; i < files.length; i++) {
                        formdata.append(files[i].name, files[i]);
                    }

                    $.ajax({
                        url: '@Url.Action("Upload_otesatCdrSave","Rejections")',
                        type: 'POST',
                        contentType: false,
                        processData: false,
                        data: formdata,
                        success: function (result) {
                            alert(result);
                        },
                        error: function (xhr, status, text) {
                            alert("Error: Xhr Status: " + xhr.status + " Status: " + status + " test: " + text);
                        }
                    });
                }
            }
        });
    </script>
}