FormUpdated/Controllers/CrewController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FormUpdated.Areas.LDKSatcom.Models;
using FormUpdated.Models;

namespace FormUpdated.Controllers
{
    public class CrewController : Controller
    {
        private NoonReportFormatEntities db = new NoonReportFormatEntities();

        // GET: Crew
        public ActionResult Index()
        {
            return View(db.CrewDetails.ToList());
        }

        // GET: Crew/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CrewDetail crewDetail = db.CrewDetails.Find(id);
            if (crewDetail == null)
            {
                return HttpNotFound();
            }
            return View(crewDetail);
        }

        // GET: Crew/Create
        public ActionResult Create()
        {
            if (!string.IsNullOrEmpty(MySession.curVessel) && !string.IsNullOrEmpty(MySession.curCompany))
            {
                CrewDetail crewDetail = new CrewDetail();
                string OrderKeyShip = string.Empty;
                string OrderKeyShore = string.Empty;

                List<CrewDetail> lstCrew = db.CrewDetails.Where(t => t.CompanyName.Equals(MySession.curCompany) && t.ShipName.Equals(MySession.curVessel)).ToList();
                foreach (var crews in lstCrew)
                {
                    if (crews.Type.ToLower().Equals("ship") && !string.IsNullOrEmpty(crews.OrderKey))
                        OrderKeyShip = crews.OrderKey;
                    else if (crews.Type.ToLower().Equals("shore") && !string.IsNullOrEmpty(crews.OrderKey))
                        OrderKeyShore = crews.OrderKey;

                    if (!string.IsNullOrEmpty(OrderKeyShip))
                        crewDetail.OrderKey = OrderKeyShip;
                    else if (!string.IsNullOrEmpty(OrderKeyShore))
                        crewDetail.OrderKey = OrderKeyShore;
                }
                return View(crewDetail);
            }

            return View();
        }

        // POST: Crew/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Title,DateofJoining,LeavingDate,AccessLevel,IsSuspension,UserName,Password,EmailID,CompanyName,ShipName,Type,Tomail,CCMail,OrderKey,isAdmin")] CrewDetail crewDetail)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(crewDetail.OrderKey))
                {
                    crewDetail.OrderKey = Helper.GetOrderID();
                }
                db.CrewDetails.Add(crewDetail);
                db.SaveChanges();
                ViewBag.OrderKeys = crewDetail.OrderKey;
                return View("Create");
            }

            return View(crewDetail);
        }

        // GET: Crew/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CrewDetail crewDetail = db.CrewDetails.Find(id);
            if (crewDetail == null)
            {
                return HttpNotFound();
            }

            TempData["DateofJoining"] = crewDetail.DateofJoining;
            TempData["LeavingDate"] = crewDetail.LeavingDate;
            return View(crewDetail);
        }

        // POST: Crew/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Title,DateofJoining,LeavingDate,AccessLevel,IsSuspension,UserName,Password,EmailID,CompanyName,ShipName,Type,Tomail,CCMail,isAdmin")] CrewDetail crewDetail)
        {
            if (ModelState.IsValid)
            {
                if (TempData["DateofJoining"] != null && crewDetail.DateofJoining == null)
                    crewDetail.DateofJoining = Convert.ToDateTime(TempData["DateofJoining"]);

                if (TempData["LeavingDate"] != null && crewDetail.LeavingDate == null)
                    crewDetail.LeavingDate = Convert.ToDateTime(TempData["LeavingDate"]);

                db.Entry(crewDetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(crewDetail);
        }

        // GET: Crew/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CrewDetail crewDetail = db.CrewDetails.Find(id);
            if (crewDetail == null)
            {
                return HttpNotFound();
            }
            return View(crewDetail);
        }

        // POST: Crew/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CrewDetail crewDetail = db.CrewDetails.Find(id);
            db.CrewDetails.Remove(crewDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FormUpdated/Controllers/demoNoonReportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.IO.Compression;
using System.IO;
using System.IO.Packaging;
using FormUpdated.Areas.LDKSatcom.Models;

namespace FormUpdated.Controllers
{
    public class demoNoonReportsController : Controller
    {
        private Areas.LDKSatcom.Models.NoonReportFormatEntities db = new Areas.LDKSatcom.Models.NoonReportFormatEntities();

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult AuthLogin(FormCollection form, string returnUrl)
        {
            string loginname = form["txtLoginName"];
            string password = form["txtPassword"];
            string remember = form["remember"];
            string orderID = form["txtOrderId"];

            MySession.InvoiceLogoPath = Server.MapPath("../Images/smts logo.jpg");
            
            try
            {
                if (!string.IsNullOrEmpty(loginname) && !string.IsNullOrEmpty(password))
                {
                    Areas.LDKSatcom.Models.CrewDetail Crew = new Areas.LDKSatcom.Models.CrewDetail();
                    
                    if (loginname.Equals("admin") && password.Equals("admin"))
                    {
                        Crew = db.CrewDetails.FirstOrDefault(t => ((t.UserName.Equals(loginname) || t.EmailID.Equals(loginname)) &&
                                                                        t.Password.Equals(password) ));
                    }
                    else
                    {
                        Crew = db.CrewDetails.FirstOrDefault(t => ((t.UserName.Equals(loginname) || t.EmailID.Equals(loginname)) &&
                                                                        t.Password.Equals(password) && t.OrderKey.Equals(orderID)));
                    }

                    if(Crew == null)
                    {
                        Crew = db.CrewDetails.FirstOrDefault(t => ((t.UserName.Equals(loginname) || t.EmailID.Equals(loginname)) &&
                                                                       t.Password.Equals(password)));
                        if(Crew != null)
                        {
                            if (!Crew.isBilling)
                                Crew = null;
                        }
                    }

                    if (Crew != null)
                    {
                        FormsAuthentication.SetAuthCookie(Crew.UserName, string.IsNullOrEmpty(remember) ? false : remember.Contains("on") ? true : false);

                        if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1 && returnUrl.StartsWith("/") && !returnUrl.StartsWith("//"))
                            return Redirect(returnUrl);

                        if (Crew.isBilling)
                        {
                            //return RedirectToAction("NewOteSat2CDR", "CDR", new { area = "BillingSystem" });
                            //return RedirectToAction("otesatCdrtoCt", "Rejections", new { area = "BillingSystem" });
                            return RedirectToAction("CDRtoCT", "CommonTable", new { area = "BillingSystem" });
                        }
                        else
                        {
                            MySession.AccessLevel = Crew.AccessLevel;

                            if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1 && returnUrl.StartsWith("/") && !returnUrl.StartsWith("//"))
                                return Redirect(returnUrl);
                            else if (Crew.isAdmin.Equals(true))
                            {
                                MySession.isAdmin = true;
                                MySession.curCompany = null;
                                MySession.curVessel = null;
                                MySession.EmailID = Crew.EmailID;
                                MySession.Password = Crew.Password;
                                //return RedirectToAction("companyDashboard", "DemoReports");
                                return RedirectToAction("companyDashboard", "DemoReports", new { area = "LDKSatcom" });
                            }
                            else
                            {
                                MySession.isAdmin = false;
                                MySession.curCompany = Crew.CompanyName;
                                MySession.AccessLevel = Crew.AccessLevel;
                                MySession.EmailID = Crew.EmailID;
                                MySession.Password = Crew.Password;
                                //return RedirectToAction("shipDashboard", "DemoReports");
                                return RedirectToAction("shipDashboard", "DemoReports", new { area = "LDKSatcom" });
                            }
                        }
                    }
                    else
                    {
                        TempData["Message"] = "The username or password and orderid is incorrect.";
                        return RedirectToAction("Login");
                    }
                }
                else
                {
                    TempData["Message"] = "The username or password and orderid is incorrect.";
                    return RedirectToAction("Login");
                }
            }
            catch (Exception err)
            {
                MySession.isAdmin = true;
                TempData["Message"] = "The username or password and orderid is incorrect.";
                return RedirectToAction("Login");
            }
        }

        [Authorize]
        [AllowAnonymous]
        public ActionResult logout()
        {
            MySession.isAdmin = true;
            Response.Cache.SetNoStore();
            FormsAuthentication.SignOut();
            return Redirect("Login");
        }

        public ActionResult shipDashboard(string companyName)
        {
            if (!string.IsNullOrEmpty(companyName))
            {
                MySession.curCompany = companyName;
                ViewBag.VesselNames = db.CrewDetails.Where(t => t.CompanyName.Equals(companyName)).Select(t => t.ShipName).Distinct().ToList();
            }
            else if (!string.IsNullOrEmpty(MySession.curCompany))
                ViewBag.VesselNames = db.CrewDetails.Where(t => t.CompanyName.Equals(MySession.curCompany)).Select(t => t.ShipName).Distinct().ToList();

            return View();
        }

        public ActionResult companyDashboard()
        {
            try
            {
                if (MySession.isAdmin)
                    ViewBag.CompanyNames = db.CrewDetails.Where(t => t.CompanyName != string.Empty).Select(t => t.CompanyName).Distinct().ToList();
                else
                    return RedirectToAction("shipDashboard", new { MySession.curCompany });
            }
            catch
            {
                ViewBag.CompanyNames = db.CrewDetails.Select(t => t.CompanyName).Distinct().ToList();
            }
            return View();
        }

        public ActionResult DashBoard(string shipName)
        {
            if (!string.IsNullOrEmpty(shipName))
            {
                TempData["VesselName"] = shipName;
                MySession.curVessel = shipName;
            }
            else
                TempData["VesselName"] = string.Empty;

            return View();
        }

        // GET: demoNoonReports
        public ActionResult Index(int id)
        {
            try
            {
                TempData["SelectReport"] = id;
                string shipName = string.Empty;
                if (TempData["VesselName"] != null && !string.IsNullOrEmpty(Convert.ToString(TempData["VesselName"])))
                {
                    shipName = TempData["VesselName"].ToString();
                    TempData.Keep("VesselName");
                }
                else
                {
                    shipName = MySession.curVessel;
                }

                if (!string.IsNullOrEmpty(shipName))
                {
                    if (id == 1)
                        return View(db.demoNoonReports.Where(t => t.ReportType.Equals("Morning") && t.ShipName.Equals(shipName)).ToList());
                    else if (id == 2)
                        return View(db.demoNoonReports.Where(t => t.ReportType.Equals("Noon") && t.ShipName.Equals(shipName)).ToList());
                    else
                        return View(db.demoNoonReports.Where(t => t.ShipName.Equals(shipName)).ToList());
                }
                else
                    return View(db.demoNoonReports.Where(t => t.ShipName.Equals(shipName)).ToList());


            }
            catch (Exception error)
            {
                return View("DashBoard");
            }
        }

        [HttpGet]
        public virtual ActionResult Download(int id)
        {
            if (TempData["VesselName"] != null)
                TempData.Keep("VesselName");

            int ReportTypeID = 1;

            if (TempData["SelectReport"] != null)
                ReportTypeID = Convert.ToInt32(TempData["SelectReport"]);

            if (id > 0)
            {
                var attach = (from att in db.AttachFiles
                              where (att.NRid.Equals(id))
                              select new { att.FileNames, att.ContentType, att.Data }).ToList();
                if (attach != null)
                {
                    foreach (var attaches in attach)
                    {
                        return File(attaches.Data, attaches.ContentType, attaches.FileNames);
                    }
                    return RedirectToAction("Index", new { id = ReportTypeID });
                }
                else

FormUpdated/Areas/BillingSystem/Views/Shared/_Layout_Search.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title> Invoices </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<style type="text/css">
    .fontStyle {
        color: whitesmoke !important;
        font-family: initial;
        font-weight: 100;
        font-size: 20px;
    }

    .whitefont {
        color: whitesmoke !important;
    }

    #nav ul {
        display: none;
    }

    #nav li:hover > ul {
        display: block;
    }

    .dropdown-submenu {
        position: relative;
    }

        .dropdown-submenu .dropdown-menu {
            top: 0;
            left: 100%;
            margin-top: -1px;
        }
</style>

<body>
    <div style="padding:0; margin:0;">
        <div class="navbar navbar-inverse navbar-fixed-top" style="background-color:#337ab7;border-width:0px;border-color:none !important;">
            @Html.Partial("_Menuitems_Partial")
        </div>

        <div>
            @RenderBody()
        </div>

        <div align="center" style="padding:20px;">
            <footer class="panel-footer">
                <p>&copy; @DateTime.Now.Year - SMTS Pvt Ltd Billing System</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        </div>
</body>
</html>

FormUpdated/Areas/BillingSystem/Views/Shared/_Loyout_BS.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Billing</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<style type="text/css">
    .fontStyle {
        color: whitesmoke !important;
        font-family: initial;
        font-weight: 100;
        font-size: 20px;
    }

    .whitefont {
        color: whitesmoke !important;
    }

    #nav ul {
        display: none;
    }

    #nav li:hover > ul {
        display: block;
    }

    .dropdown-submenu {
        position: relative;
    }

        .dropdown-submenu .dropdown-menu {
            top: 0;
            left: 100%;
            margin-top: -1px;
        }
</style>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color:#337ab7;border-width:0px;border-color:none !important;">
        @Html.Partial("_Menuitems_Partial")
    </div>
   
    <div class="container body-content" style="min-height:550px;margin-top:10px;">
        @RenderBody()
    </div>

    <div align="center" style="padding:20px;">
        <footer class="panel-footer">
            <p>&copy; @DateTime.Now.Year - SMTS Pvt Ltd Billing System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FormUpdated/Areas/BillingSystem/Views/Shared/_Menuitems_Partial.cshtml
<div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        @Html.ActionLink("Billing System", "Invoices", "Index", new { area = "BillingSystem" }, new { @class = "navbar-brand fontStyle" })
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav" id="nav" style="font-weight:bold;">

            @*@{
            var myTag = MySession.isAdmin;
        }
        @if (myTag)
        {
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color:whitesmoke"> Crew <b class="caret"></b></a>
                <ul class="dropdown-menu" style="z-index:101;height:auto">
                    <li>@Html.ActionLink("New Crew", "Create", "Crew")</li>
                    <li>@Html.ActionLink("Crew Details", "Index", "Crew")</li>
                </ul>
            </li>
        }*@

            <li class="dropdown-submenu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span style=" color: whitesmoke !important;">Common Table</span><b class="caret fontStyle"></b></a>
                <ul class="dropdown-menu">
                    @*<li>@Html.ActionLink("OteSat to CDR", "OteSatCDR", "CDR")</li>*@
                    <li>@Html.ActionLink("OteSat to CT", "NewOteSat2CDR", "CDR")</li>
                    <li>@Html.ActionLink("IMARSat to CDR", "ImarSatCDR", "CDR")</li>
                    <li>@Html.ActionLink("NSSL Global to CDR", "NSSLCDR", "CDR")</li>
                    <li>@Html.ActionLink("NI CDR to CT", "NIToCDR", "CDR")</li>
                    <li>@Html.ActionLink("EvoSat CDR to CT", "EvoSatCDRToCT", "CDR")</li>
                </ul>
            </li>

            <li class="dropdown-submenu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span style=" color: whitesmoke !important;">Customers</span><b class="caret fontStyle"></b></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("New Customers", "Index", "Customers")</li>
                    <li>@Html.ActionLink("Customer Contracts", "Index", "CusContracts")</li>
                    <li>@Html.ActionLink("Customer Registers", "Index", "CusRegs_")</li>
                    <li>@Html.ActionLink("Service Types", "Index", "CusServiceTypes")</li>
                    <li>@Html.ActionLink("CUS Reg Price", "CUSRegPrices", "View")</li>
                </ul>
            </li>

            <li class="dropdown-submenu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span style=" color: whitesmoke !important;">LES</span><b class="caret fontStyle"></b></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("New LES", "Index", "ServiceProviders")</li>
                    <li>@Html.ActionLink("LES Contracts", "Index", "Contracts")</li>
                    <li>@Html.ActionLink("SIM Registeration", "Index", "SimRegs")</li>
                    <li>@Html.ActionLink("LES Registeration", "Index", "SPLesRegs")</li>
                    <li>@Html.ActionLink("Service Types", "Index", "LESServiceTypes")</li>
                    <li>@Html.ActionLink("LESS Reg Price", "LESRegPrices", "View")</li>
                </ul>
            </li>

            <li class="dropdown-submenu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span style=" color: whitesmoke !important;">Secondary Table</span><b class="caret fontStyle"></b></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Invoice", "Invoice", "Invoices")</li>
                    <li>@Html.ActionLink("Rejection", "Rejection", "Rejections")</li>
                    <li>@Html.ActionLink("Manual Invoice", "ManualInvoice", "ManualInvoices")</li>
                    <li>@Html.ActionLink("OteSat Invoice", "Index", "Invoices")</li>
                    <li>@Html.ActionLink("OteSat Rejection", "Index", "Rejections")</li>
                </ul>
            </li>

            <li class="dropdown-submenu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span style=" color: whitesmoke !important;">Master Table</span><b class="caret fontStyle"></b></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Communication Type", "Index", "CommunicationTypes")</li>
                    <li>@Html.ActionLink("Units", "Index", "Units")</li>
                    <li>@Html.ActionLink("Code Kind of Traffic", "Index", "CodeKindTraffic")</li>
                    <li>@Html.ActionLink("Call Type Code", "Index", "CallTypeCodes")</li>
                    <li>@Html.ActionLink("Facility Code", "Index", "FacilityCodes")</li>
                    <li>@Html.ActionLink("Service Code", "Index", "ServiceCodes")</li>
                    <li>@Html.ActionLink("Country Code", "Index", "CountryCodes")</li>
                    <li>@Html.ActionLink("Ocean Region", "Index", "OceanRegions")</li>
                </ul>
            </li>

            <li class="dropdown-submenu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span style=" color: whitesmoke !important;">Primary</span><b class="caret fontStyle"></b></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Cus Register", "Create", "CusRegs")</li>
                    @*<li>@Html.ActionLink("Customer Details", "Create", "PrimaryCustomer")</li>*@
                    <li>@Html.ActionLink("Les Register", "Create", "LesRegs")</li>
                    @*<li>@Html.ActionLink("Les Details", "Create", "PrimaryLesDetails")</li>*@
                    @*<li>@Html.ActionLink("Les Std Cost Price", "Create", "PrimaryLesCp")</li>*@
                    @*<li>@Html.ActionLink("Bill", "Create", "PrimaryBills")</li>*@
                    @*<li>@Html.ActionLink("Dealer", "Create", "PrimaryDealer")</li>*@
                    <li>@Html.ActionLink("Ship", "Index", "Ships")</li>
                    <li>@Html.ActionLink("Staff", "Create", "StaffRegs")</li>
                    @*<li>@Html.ActionLink("FBB SIM", "Create", "PrimarySim")</li>*@
                </ul>
            </li>

            @*<li class="dropdown-submenu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span style=" color: whitesmoke !important;"> Statement </span><b class="caret fontStyle"></b></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("List", "Index", "Statements")</li>
                    <li>@Html.ActionLink("Statements", "ListStatement", "Statements")</li>
                </ul>
            </li>*@

            <li class="dropdown-submenu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span style=" color: whitesmoke !important;"> New OteSat </span><b class="caret fontStyle"></b></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("OteSat to CT", "NewOteSat2CDR", "CDR")</li>
                    <li>@Html.ActionLink("FBB Service Type", "Create", "FBBServiceTypes")</li>
                    <li>@Html.ActionLink("LES Ref", "Create", "LESRefs")</li>
                    <li>@Html.ActionLink("Satellite", "Create", "Satellites")</li>
                    <li>@Html.ActionLink("Equipment", "Create", "Equipments")</li>
                </ul>
            </li>

            <li class="dropdown-submenu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span style=" color: whitesmoke !important;"> Test </span><b class="caret fontStyle"></b></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("OteSat CDT 2 CT", "CDRtoCT", "CommonTable")</li>
                    <li>@Html.ActionLink("OteSat CDR Upload & Save", "otesatCdrSave", "Rejections")</li>
                    <li>@Html.ActionLink("OteSat CDR Download", "otesatCdrDownload", "Rejections")</li>
                    <li>@Html.ActionLink("OteSat CT Download", "otesatCTDownload", "Rejections")</li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color:whitesmoke"> @HttpContext.Current.User.Identity.Name<b class="caret"></b></a>
                <ul class="dropdown-menu" style="z-index:101;height:auto;">
                    <li>@Html.ActionLink("Logout", "logout", "demoNoonReports", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Setting", "Create", "CrewDetails", new { area = "LDKSatcom" }, null)</li>
                    <li>@Html.ActionLink("CUS Reg Upload", "CusRegUpload", "Rejections")</li>
                    <li>@Html.ActionLink("LES Reg Upload", "LesRegUpload", "Rejections")</li>
                </ul>
            </li>
        </ul>
    </div>
</div>